/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import javax.swing.UIManager;

public class pnlCompras extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public pnlCompras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        contenedorModulos = new javax.swing.JDesktopPane();
        btnproveedores = new javax.swing.JButton();
        btningres = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("COMPRAS");
        add(jLabel7);
        jLabel7.setBounds(0, 0, 1090, 51);

        javax.swing.GroupLayout contenedorModulosLayout = new javax.swing.GroupLayout(contenedorModulos);
        contenedorModulos.setLayout(contenedorModulosLayout);
        contenedorModulosLayout.setHorizontalGroup(
            contenedorModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        contenedorModulosLayout.setVerticalGroup(
            contenedorModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        add(contenedorModulos);
        contenedorModulos.setBounds(0, 124, 1090, 490);

        btnproveedores.setBackground(new java.awt.Color(255, 45, 18));
        btnproveedores.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnproveedores.setForeground(new java.awt.Color(255, 255, 255));
        btnproveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/service (1).png"))); // NOI18N
        btnproveedores.setText("Proveedores");
        btnproveedores.setBorderPainted(false);
        btnproveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproveedoresActionPerformed(evt);
            }
        });
        add(btnproveedores);
        btnproveedores.setBounds(290, 60, 140, 50);

        btningres.setBackground(new java.awt.Color(144, 209, 0));
        btningres.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btningres.setForeground(new java.awt.Color(255, 255, 255));
        btningres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/profit.png"))); // NOI18N
        btningres.setText("Ingresos");
        btningres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresActionPerformed(evt);
            }
        });
        add(btningres);
        btningres.setBounds(670, 60, 150, 50);
    }// </editor-fold>//GEN-END:initComponents
panelingresos  pnlingreso;
    private void btningresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresActionPerformed
        if(pnlingreso==null){
            pnlingreso = new panelingresos();
            contenedorModulos.add(pnlingreso);
            contenedorModulos.getDesktopManager().maximizeFrame(pnlingreso);
            pnlingreso.setVisible(true);
        }
        else{
            contenedorModulos.getDesktopManager().maximizeFrame(pnlingreso);
        }
    }//GEN-LAST:event_btningresActionPerformed
pnlproveedores panleprov;
    private void btnproveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproveedoresActionPerformed
         if(panleprov==null){
            panleprov = new pnlproveedores();
            contenedorModulos.add(panleprov);
            contenedorModulos.getDesktopManager().maximizeFrame(panleprov);
            panleprov.setVisible(true);
        }
        else{
            contenedorModulos.getDesktopManager().maximizeFrame(panleprov);
        }
    }//GEN-LAST:event_btnproveedoresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btningres;
    private javax.swing.JButton btnproveedores;
    private javax.swing.JDesktopPane contenedorModulos;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
