/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import BD.Categorias;
import Controller.CCategorias;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author najera10
 */
public class pnlCategorias extends javax.swing.JInternalFrame {

    DefaultTableModel modeloTablaCategorias = new DefaultTableModel(){
    public boolean isCellEditable(int filas, int columnas){
            if(columnas==3){
                return true;
            }else{
                return false;
            }
    }
    
    };
    Categorias bdcat = new Categorias();
    CCategorias   catrgoriaselecionado = null ;
    public pnlCategorias() {
        initComponents();
        CargarColunmas();
        CargarModeloTabla();
    }
    
        private  void CargarColunmas(){
        modeloTablaCategorias.addColumn("Nombre");
        modeloTablaCategorias.addColumn("Descripcion");
        modeloTablaCategorias.addColumn("Condicion");
        
    }

        public void CargarModeloTabla(){
      
    limpiarTabla();
       ArrayList<CCategorias>ListarCategorias = bdcat.ObtenerCategorias();
      int numerosProveedpres = ListarCategorias.size();
      modeloTablaCategorias.setNumRows(numerosProveedpres);
        for (int i = 0; i < numerosProveedpres; i++) {
            CCategorias categoria = ListarCategorias.get(i);
            String nombre = categoria.getNombre();
            String descripcion = categoria.getDescripcion();
            int condicion = categoria.getEstado();
            String estado = "";        
            if (condicion == 1){
                        estado = "Activo";
                    }else{
                        estado = "Inactivo";
                    }  
            
            modeloTablaCategorias.setValueAt(categoria, i, 0);
            modeloTablaCategorias.setValueAt(descripcion, i, 1);
            modeloTablaCategorias.setValueAt(estado, i, 2);
            
        }
         
    }
//    public void filtroBusqueda(JTextField txt) {
//        trsFiltro.setRowFilter(RowFilter.regexFilter(txt.getText()));
//    }
//
//   
    
    public void limpiar(){
        txtnombre.setText("");
        txtdescripcion.setText("");
         }
        public  void limpiarTabla(){
        int numFilas = modeloTablaCategorias.getRowCount();
        if(numFilas > 0){
            for(int i = numFilas - 1; i >= 0; i--){
                modeloTablaCategorias.removeRow(i);
            }
        }
    }
        
  
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdescripcion = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCategorias = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(900, 429));
        getContentPane().setLayout(null);

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Categorias");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 10, 1060, 65);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        jLabel1.setText("Nombre");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        jLabel2.setText("Descripcion");

        txtdescripcion.setColumns(20);
        txtdescripcion.setRows(5);
        jScrollPane2.setViewportView(txtdescripcion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtnombre)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btneliminar))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 130, 420, 250);

        tablaCategorias.setModel(modeloTablaCategorias);
        tablaCategorias.setRowHeight(25);
        tablaCategorias.setRowMargin(0);
        tablaCategorias.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tablaCategorias.getSelectionModel().addListSelectionListener(
            new ListSelectionListener(){
                public void valueChanged(ListSelectionEvent event){
                    if(!event.getValueIsAdjusting() && (tablaCategorias.getSelectedRow()>= 0) ){
                        int filaseleccionada = tablaCategorias.getSelectedRow();
                        CCategorias categoria = (CCategorias) modeloTablaCategorias.getValueAt(filaseleccionada, 0);
                        txtnombre.setText(categoria.getNombre());
                        txtdescripcion.setText(categoria.getDescripcion());

                        catrgoriaselecionado = categoria;

                    }
                }
            }   
        );
        jScrollPane1.setViewportView(tablaCategorias);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(490, 130, 580, 250);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Listado de Categorias");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(690, 90, 140, 30);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Datos de Categorias");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 90, 130, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String nombre = txtnombre.getText();
            String descripcion = txtdescripcion.getText();
            
            if (nombre.equals("") && descripcion.equals("")) {
            
                JOptionPane.showMessageDialog(null, "Verifique los datos");
            
            }else{
                
        int cuentaFilasSeleccionadas = tablaCategorias.getSelectedRowCount();
        if (cuentaFilasSeleccionadas == 1) {
            bdcat.actualizarCategoria(catrgoriaselecionado, nombre, descripcion);
             CargarModeloTabla();
             limpiar();
        }else if(cuentaFilasSeleccionadas == 0){
            CCategorias cate = new CCategorias("0",nombre,descripcion,1);
            bdcat.insert(cate);
            CargarModeloTabla();
            limpiar();
        }
            }
        } catch (SQLException ex) {
            Logger.getLogger(pnlCategorias.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
try {
            
             int cuentaFilasSeleccionadas = tablaCategorias.getSelectedRowCount();
            if (cuentaFilasSeleccionadas == 0) {
                JOptionPane.showMessageDialog(null, "Debe serleccionar alguna fila");
            }else{
                bdcat.eliminarCatedoria(catrgoriaselecionado);
                JOptionPane.showMessageDialog(null, "Categoria  eliminada");
                limpiar();
                CargarModeloTabla();
            }
            
          
        } catch (SQLException ex) {
            Logger.getLogger(pnlUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_btneliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaCategorias;
    private javax.swing.JTextArea txtdescripcion;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
