/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import BD.Clientes;
import Controller.CClientes;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.paint.Color;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RojeruSan
 */
public class pnlVentas extends javax.swing.JPanel {

    DefaultTableModel modeloTablaClientes = new DefaultTableModel(){
      public boolean isCellEditable(int filas, int columnas){
            if(columnas==4){
                return true;
            }else{
                return false;
            }
    }
    
    
    };
    Clientes  bdclt = new Clientes();
    CClientes  clienteseleccionado = null ;
     
           

       
    public pnlVentas() {
        initComponents();
        cargarColumnas();
        cargarModeloTabla();
//        btneliminar.setVisible(false);
        
        
    }

    public void cargarColumnas(){
        modeloTablaClientes.addColumn("Nombre");
        modeloTablaClientes.addColumn("Dirección");
        modeloTablaClientes.addColumn("Télefono");
        modeloTablaClientes.addColumn("Email");
    }
    
    
    
    public void cargarModeloTabla (){
         limpiarTabla();
       ArrayList<CClientes>ListarClientes = bdclt.ObtenerUsuarios();
      int numerosUsusarios = ListarClientes.size();
      modeloTablaClientes.setNumRows(numerosUsusarios);
        for (int i = 0; i < numerosUsusarios; i++) {
            CClientes cliente = ListarClientes.get(i);
            String nombre = cliente.getNombre();
            String direccion = cliente.getDireccion();
            String telefono = cliente.getTelefono();
            String email = cliente.getEmail();
            
            
            modeloTablaClientes.setValueAt(cliente, i, 0);
            modeloTablaClientes.setValueAt(email, i, 1);
            modeloTablaClientes.setValueAt(telefono, i, 2);
            modeloTablaClientes.setValueAt(email, i, 3);
        }
    }
    
       public  void limpiarTabla(){
        int numFilas = modeloTablaClientes.getRowCount();
        if(numFilas > 0){
            for(int i = numFilas - 1; i >= 0; i--){
                modeloTablaClientes.removeRow(i);
            }
        }
    }
       
       public void limpiardatos(){
           txtnombre.setText("");
           txtdireccion.setText("");
           txtemail.setText("");
           txttelefono.setText("");
          
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ventas");
        add(jLabel7);
        jLabel7.setBounds(10, 0, 883, 62);

        jLabel1.setText("Nombre:");
        add(jLabel1);
        jLabel1.setBounds(27, 115, 50, 27);
        add(txtnombre);
        txtnombre.setBounds(87, 115, 172, 26);

        jLabel2.setText("Dirección:");
        add(jLabel2);
        jLabel2.setBounds(20, 160, 60, 30);
        add(txtdireccion);
        txtdireccion.setBounds(80, 160, 258, 26);

        jLabel3.setText("Telefono");
        add(jLabel3);
        jLabel3.setBounds(354, 166, 60, 14);
        add(txttelefono);
        txttelefono.setBounds(420, 160, 213, 26);

        jLabel4.setText("Email");
        add(jLabel4);
        jLabel4.setBounds(640, 160, 40, 24);
        add(txtemail);
        txtemail.setBounds(680, 160, 218, 26);

        tablaClientes.setModel(modeloTablaClientes);
        tablaClientes.setRowHeight(25);
        tablaClientes.setRowMargin(0);
        tablaClientes.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tablaClientes.getSelectionModel().addListSelectionListener(
            new ListSelectionListener(){
                public void valueChanged(ListSelectionEvent event){
                    if(!event.getValueIsAdjusting() && (tablaClientes.getSelectedRow()>= 0) ){
                        int filaseleccionada = tablaClientes.getSelectedRow();
                        CClientes cliente = (CClientes) modeloTablaClientes.getValueAt(filaseleccionada, 0);
                        txtnombre.setText(cliente.getNombre());
                        txtdireccion.setText(cliente.getDireccion());
                        txtemail.setText(cliente.getEmail());
                        txttelefono.setText(cliente.getTelefono());
                        clienteseleccionado = cliente;

                    }
                }
            }   
        );
        tablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaClientes);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 260, 1070, 214);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Control Clientes");
        add(jLabel5);
        jLabel5.setBounds(20, 68, 219, 24);

        btnguardar.setBackground(new java.awt.Color(51, 102, 255));
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        add(btnguardar);
        btnguardar.setBounds(280, 210, 100, 38);

        btneliminar.setBackground(new java.awt.Color(255, 0, 0));
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        add(btneliminar);
        btneliminar.setBounds(400, 210, 100, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
       
        try {
            String nombre = txtnombre.getText();
            String direccion = txtdireccion.getText();
            String telefono = txttelefono.getText();
            String email = txtemail.getText();
            
            
               int cuentaFilasSeleccionadas = tablaClientes.getSelectedRowCount(); 
           

        if (cuentaFilasSeleccionadas == 1) {
             bdclt.actualizarProveedor(clienteseleccionado, nombre, direccion, telefono, email);
            cargarModeloTabla();
            limpiardatos();
            
        }else if(cuentaFilasSeleccionadas == 0){
             CClientes clientes = new CClientes(0,nombre,"","",direccion,telefono,email);
            bdclt.insert(clientes);
            cargarModeloTabla();
            limpiardatos();
                    }
        } catch (SQLException ex) {
            Logger.getLogger(pnlVentas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
    }//GEN-LAST:event_btnguardarActionPerformed

    private void tablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClientesMouseClicked
//       int cuentaFilasSeleccionadas = tablaClientes.getSelectedRowCount(); 
//        System.out.println("Hay seleccionadas: " + cuentaFilasSeleccionadas + " filas");
//
//        if (cuentaFilasSeleccionadas == 1) { 
//            btnguardar.setText("Editar");
//            btnguardar.setBackground(new java.awt.Color(255,252,51));
//            btnguardar.setSize(69, 23);
//            btneliminar.setVisible(true);
//
//            int indiceFilaSeleccionada = tablaClientes.getSelectedRow(); 
//            System.out.println("Fila seleccionada: " + indiceFilaSeleccionada);
//        } 
    }//GEN-LAST:event_tablaClientesMouseClicked

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        try {
            bdclt.eliminarcliente(clienteseleccionado);
            cargarModeloTabla();
            limpiardatos();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(pnlVentas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btneliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
